roschaefer/story.board

.gitignore, app/controllers/sensors_controller.rb, app/models/sensor.rb, app/models/sensor_type.rb, app/views/sensors/_form.html.haml, app/views/sensors/show.html.haml, db/migrate/20160524152055_create_sensor_types.rb, db/migrate/20160524152647_add_sensor_type_id_to_sensor.rb, db/migrate/20160524155737_drop_obsolete_columns_in_sensor.rb, db/schema.rb, features/select_sensor_type.feature, features/step_definitions/steps.rb, spec/factories/sensor.rb, spec/factories/sensor_types.rb
fixes #9 
@drjakob I called the new model ``SensorType`` which is a bit vague, to my taste. Anyways, we can add more attributes to the model if we know them from for all our customer in advance.
=> 9 new model sensor type

Gemfile, Gemfile.lock, app/assets/javascripts/application.js, app/controllers/text_components_controller.rb, app/models/condition.rb, app/models/text_component.rb, app/views/text_components/_condition_fields.html.haml, app/views/text_components/_form.html.haml, db/migrate/20160524231702_create_conditions.rb, db/schema.rb, features/connect_text_component_with_condition.feature, features/select_sensor_type.feature, features/step_definitions/steps.rb, features/support/env.rb, spec/factories/conditions.rb, spec/factories/text_components.rb
=> 17 connect with condition

app/models/sensor.rb, spec/models/sensor_spec.rb
=> bugfix: proper uniquness validation of sensor name

app/controllers/report_controller.rb, app/models/sensor.rb, app/views/report/show.html.haml, features/choose_text_components_by_condition.feature, features/show_report_on_landing_page.feature, features/step_definitions/steps.rb, spec/models/sensor_spec.rb
fix: #18 
@drjakob: It would be great if we had seed data for text components. Could you provide some? Then we could see these kind of changes in the live system.
CSV is just fine. I can turn it into seed data.
=> 18 choose text components by condition

Gemfile, Gemfile.lock, config/database.yml, db/schema.rb
about to close, but test after merge into master #44
=> add gem pg, switch production db in database.yml, update schema.rb

Gemfile, Gemfile.lock, app/controllers/sensor_readings_controller.rb, app/controllers/sensors_controller.rb, app/views/sensor/readings/_reading.html.haml, app/views/sensor/readings/fake.js.erb, app/views/sensors/_generate_fake_sample_data.html.haml, app/views/sensors/index.html.haml, app/views/sensors/show.html.haml, config/routes.rb, features/generate_fake_sample_data.feature, features/step_definitions/steps.rb, features/support/env.rb, spec/requests/generate_fake_sample_data_spec.rb
=> Generate fake sensor data

app/assets/javascripts/sensors.coffee, app/models/sensor/reading.rb, app/views/sensors/_generate_fake_sample_data.html.haml, spec/factories/sensor/reading.rb, spec/requests/generate_fake_sample_data_spec.rb
bugfix upper lower bound sanity check
hide/unhide generate fake sample data form
=> Hide sample data form

app/controllers/sensor_readings_controller.rb, app/controllers/sensors_controller.rb, app/models/sensor/reading.rb, app/views/sensor/readings/fake.js.erb, app/views/sensors/show.html.haml, db/migrate/20160603220304_add_enum_source_to_sensor_reading.rb, db/schema.rb, features/generate_fake_sample_data.feature, features/step_definitions/steps.rb
=> 12 choose between databases

.gitignore, app/controllers/reports_controller.rb, app/models/sensor.rb, app/views/layouts/application.html.haml, config/routes.rb, features/preview.feature, features/step_definitions/steps.rb
=> 31 preview

app/controllers/sensor_readings_controller.rb, features/sensor_readings_api/particle_json.feature
=> 56 change api

app/controllers/sensor_readings_controller.rb, spec/factories/sensor.rb, spec/requests/assign_sensor_by_address_spec.rb
=> 59 bug wrong assignment of sensor

app/controllers/sensors_controller.rb, app/views/sensor/readings/_reading.html.haml, app/views/sensors/show.html.haml, features/sensors/limit_number_of_sensor_readings.feature, features/step_definitions/steps.rb
=> 60 limit sensor readings

Gemfile, Gemfile.lock, Guardfile, app/controllers/reports_controller.rb, app/controllers/sensor_readings_controller.rb, app/decorators/sensor_decorator.rb, app/models/condition.rb, app/models/report.rb, app/models/sensor.rb, app/models/sensor/reading.rb, app/models/text_component.rb, config/application.rb, db/migrate/20160731224759_rename_column_source_to_intention.rb, db/schema.rb, features/step_definitions/steps.rb, features/text_components/write_about_sensor_value.feature, lib/text/generator.rb, spec/decorators/sensor_decorator_spec.rb, spec/models/report_spec.rb, spec/models/sensor_spec.rb, spec/models/text_component_spec.rb, spec/text/generator_spec.rb
=> 23 write about actual sensor value

features/step_definitions/steps.rb, features/text_components/write_about_sensor_value.feature
=> green: fix/unwip cucumber test write about actual sensor value

app/controllers/reports_controller.rb, app/views/reports/_form.html.haml, app/views/reports/present.html.haml, app/views/reports/show.html.haml, db/migrate/20160804220913_add_video_stream_to_report.rb, db/schema.rb, features/reports/embed_livestream.feature, features/step_definitions/steps.rb, features/text_components/write_about_sensor_value.feature
=> 77 embed livestream

app/controllers/text_components_controller.rb, app/models/condition.rb, app/models/sensor.rb, app/models/text_component.rb, app/views/text_components/_form.html.haml, app/views/text_components/show.html.haml, db/migrate/20160804225417_add_timeliness_constraint_to_text_component.rb, db/schema.rb, features/reports/timeliness_constrain.feature, features/step_definitions/steps.rb, features/text_components/timeliness_constraint.feature
=> 76 add timeliness constraint

Capfile, Gemfile, Gemfile.lock, app/controllers/reports_controller.rb, app/models/record.rb, app/models/report.rb, app/views/reports/present.html.haml, config/deploy.rb, config/schedule.rb, db/migrate/20160807144051_create_records.rb, db/migrate/20160807152151_add_intention_to_records.rb, db/schema.rb, features/reports/archive.feature, features/reports/timeliness_constrain.feature, features/step_definitions/steps.rb, features/support/env.rb, features/text_components/choose_text_components_by_condition.feature, features/text_components/write_about_sensor_value.feature, lib/tasks/archive.rake, spec/factories/records.rb, spec/jobs/whenever_spec.rb, spec/models/report_spec.rb
=> 20 archive reports

app/models/report.rb, features/step_definitions/steps.rb, features/text_components/write_about_report_name.feature, lib/text/generator.rb, spec/text/generator_spec.rb
might close #83 
@drjakob same questions like in #89
=> green cucumber and spec: #83, refactor TextGenerator to have state

app/models/text_component.rb, features/reports/heading.feature, features/step_definitions/steps.rb, lib/text/generator.rb, spec/text/generator_spec.rb
=> 87 choose only one heading

app/controllers/reports_controller.rb, app/models/report.rb, app/views/reports/_form.html.haml, app/views/reports/_variables.html.haml, app/views/reports/new.html.haml, app/views/reports/show.html.haml, features/reports/variables.feature, features/step_definitions/steps.rb, features/text_components/write_about_custom_variables.feature
=> 82 edit custom variables

app/models/sensor.rb, app/views/sensors/index.html.haml, app/views/sensors/show.html.haml, app/views/text_components/_condition_fields.html.haml, db/migrate/20160906224205_change_markup_from_sensor_name_to_sensor_id.rb, db/schema.rb, features/step_definitions/steps.rb, features/text_components/write_about_sensor_value.feature, lib/text/generator.rb, spec/text/generator_spec.rb
=> 122 markup with sensor

app/controllers/reports_controller.rb
=> fix order of archived reports

app/controllers/text_components_controller.rb, app/decorators/event_decorator.rb, app/models/event.rb, app/models/report.rb, app/models/text_component.rb, app/views/reports/present.html.haml, app/views/sensors/_form.html.haml, app/views/text_components/_form.html.haml, features/step_definitions/steps.rb, features/text_components/write_about_an_event.feature, lib/text/generator.rb, spec/text/generator_spec.rb
=> 120 text component connect with events

app/controllers/reports_controller.rb, app/decorators/sensor_decorator.rb, app/models/report.rb, app/models/sensor.rb, app/models/sensor/reading.rb, app/models/text_component.rb, features/reports/time_travel.feature, features/step_definitions/steps.rb, lib/tasks/archive.rake, lib/text/generator.rb, spec/decorators/sensor_decorator_spec.rb, spec/models/report_spec.rb, spec/models/sensor_spec.rb, spec/models/text_component_spec.rb, spec/text/generator_spec.rb
=> 97 read about any point in time

app/views/reports/present.html.haml, features/reports/subheadings.feature, features/step_definitions/steps.rb, features/text_components/write_about_sensor_value.feature, lib/text/generator.rb
=> 108 insert break and subheading

lib/text/generator.rb
=> Report>>Main Part: fix proper nesting of paragraphs

app/controllers/reports_controller.rb, app/models/report.rb, app/views/reports/_form.html.haml, app/views/reports/show.html.haml, db/migrate/20161004043253_add_duration_to_report.rb, db/schema.rb, features/reports/report_settings_page.feature, features/step_definitions/steps.rb
=> 157 end date of report

Gemfile, Gemfile.lock, app/models/text_component.rb, features/reports/time_span.feature, features/step_definitions/steps.rb, features/support/env.rb
=> 187 timespan

app/controllers/triggers_controller.rb, app/models/trigger.rb, app/views/triggers/_form.html.haml, app/views/triggers/show.html.haml, db/migrate/20161123131246_add_hours_to_triggers.rb, db/schema.rb, features/reports/time_of_the_day.feature, features/step_definitions/steps.rb, spec/models/trigger_spec.rb
=> 187 time of the day

app/assets/stylesheets/text_components.scss, app/views/text_components/_form.html.haml, app/views/text_components/index.html.haml
=> 224 226 style adjustments and buttons

app/assets/stylesheets/application.css, app/controllers/text_components_controller.rb, app/views/text_components/_form.html.haml, app/views/text_components/index.html.haml, app/views/text_components/show.html.haml, app/views/triggers/_trigger.html.haml, features/step_definitions/steps.rb, spec/requests/text_components_spec.rb, spec/views/text_components/index.html.haml_spec.rb
=> 225 advanced dropdown menu

app/views/triggers/_trigger_fields.html.haml
=> limit options in dropdown to 0..23

Gemfile.lock, app/controllers/channels_controller.rb, config/routes.rb, cucumber.yml, features/channels/api.feature, features/step_definitions/steps.rb, lib/tasks/cucumber.rake, spec/controllers/channels_controller_spec.rb
this is a piece of dummy code in order to set up a ChatFuel
@leifg I would actually like to merge this into master first, to have something we can point Chatfuel to
=> 258 call a channel

app/views/text_components/_form.html.haml, app/views/triggers/_form.html.haml, app/views/triggers/_trigger_fields.html.haml, spec/views/text_components/index.html.haml_spec.rb
That was an actual bug in a view
fix #220
@leifg review please
=> 220 ux fail buttons

app/controllers/text_components_controller.rb, app/controllers/triggers_controller.rb, app/models/report.rb, app/views/text_components/_form.html.haml, app/views/triggers/_trigger_fields.html.haml, spec/models/report_spec.rb
=> fix #180 and decomplexify code, visible report association - why not?

app/controllers/text_components_controller.rb, app/views/text_components/_form.html.haml, app/views/triggers/_form.html.haml, app/views/triggers/_trigger_fields.html.haml, spec/controllers/text_components_controller_spec.rb, spec/views/text_components/index.html.haml_spec.rb
=> 277 double report input fields

lib/tasks/channel.rake, spec/controllers/channels_controller_spec.rb
this is only for dev purposes. Name in production has already been
changed
=> Rename storyboard channel to sensorstory

app/lib/text/generator.rb, app/models/channel.rb, app/models/report.rb, app/models/text_component.rb, features/step_definitions/steps.rb, features/text_components/choose_channel.feature, spec/controllers/reports_controller_spec.rb, spec/controllers/text_components_controller_spec.rb, spec/factories/channels.rb, spec/factories/text_components.rb, spec/jobs/whenever_spec.rb, spec/models/channel_spec.rb, spec/models/report_spec.rb, spec/models/text_component_spec.rb, spec/text/generator_spec.rb, spec/views/text_components/index.html.haml_spec.rb, spec/views/text_components/show.html.haml_spec.rb
this is a pretty messy solution. I am currently not aware of a better
solution though.
=> Remove text components from sensorstory if they are not in the right channel

app/controllers/channels_controller.rb, app/controllers/chatbot_controller.rb, app/controllers/chatfuel_controller.rb, app/lib/text/generator.rb, app/lib/text/renderer.rb, app/lib/text/sorter.rb, app/models/report.rb, app/models/text_component.rb, config/routes.rb, features/channels/api.feature, features/step_definitions/steps.rb, spec/controllers/chatfuel_controller_spec.rb, spec/text/renderer_spec.rb, spec/text/sorter_spec.rb
To try it out do the following:
- Create a chatbot channel:
`Channel.create(name: "chatbot", description: "Channel for Chatbot", report: Report.current)`
- Add channel to text component.
- Add Topic "milk_quality" to text component
- Download [ngrok](https://ngrok.com/)
- Start ngrok and configure it to your local rails port: `ngrok http -subdomain=kuhbertha 3000`
- Click the "Wer bist Du?" Button in Chatbot
After introduction The text component main part should be visible
close #259
=> Implement chatbot responses

db/seeds.rb
Added missing channel data to seeds.rb, so the project can find the necessary channels and work as expected locally,
=> added missing channel data to seeds.rb

app/models/text_component.rb, app/views/text_components/show.html.haml
@leifg I try to use `delegate` in order to avoid Nilpointer Exceptions. In this case here it shows a blank `topic` field in the view if there is no topic, which also gives some information..
=> use delegate in TextComponent model and show blank topic in view

spec/factories/sensor.rb, spec/factories/triggers.rb, spec/models/trigger_spec.rb
close #175 
@drjakob no behaviour has changed. Here are some more software tests to ensure the constraint is working properly.
=> create a test to check the timeliness_constraint

app/assets/javascripts/triggers.js
fix #204
@leifg I have no idea how to test this. You?
=> Add event listeners on page load

.travis.yml, Gemfile, Gemfile.lock, app/controllers/text_components_controller.rb, app/models/application_record.rb, app/models/question_answer.rb, app/models/text_component.rb, app/views/question_answers/_fields.html.haml, app/views/question_answers/_question_answer.html.haml, app/views/text_components/_form.html.haml, app/views/text_components/_question_answer_fields.html.haml, app/views/text_components/show.html.haml, db/migrate/20170331165247_create_question_answers.rb, db/schema.rb, features/step_definitions/steps.rb, features/support/env.rb, features/text_components/add_question_answer.feature, spec/controllers/text_components_controller_spec.rb, spec/factories/question_answers.rb, spec/models/question_answer_spec.rb, spec/models/text_component_spec.rb
=> Add model Question/Answer

app/lib/text/generator.rb, app/models/record.rb, app/views/records/_record.html.haml, app/views/records/_split_part.html.haml, app/views/reports/present.html.haml, spec/factories/records.rb, spec/models/record_spec.rb, spec/text/generator_spec.rb
mere refactoring
goals:
* don't concatenate strings - use partials (haml & friends)
* text result of Text:Generator
=> Refactor text generator with programmatic partials

app/lib/text/generator.rb, app/lib/text/renderer.rb, app/models/question_answer.rb, app/views/records/_question_answers.html.haml, spec/text/generator_spec.rb, spec/text/renderer_spec.rb
=> 112 markup in heading and question answers

db/migrate/20170516111707_add_more_default_reports.rb, db/schema.rb
=> add three default reports

app/controllers/text_components_controller.rb, app/models/text_component.rb, app/views/text_components/_form.html.haml, app/views/text_components/_text_component.html.haml, db/migrate/20170516131349_add_assignee_to_text_component.rb, db/schema.rb, features/step_definitions/steps.rb, features/text_components/assignee.feature, spec/factories/users.rb
=> 315 assignee

.gitignore, app/controllers/text_components_controller.rb, app/views/layouts/application.html.haml, app/views/text_components/_text_component_row.html.haml, app/views/text_components/index.html.haml, features/step_definitions/steps.rb, features/text_components/assignee.feature, spec/controllers/text_components_controller_spec.rb, spec/views/text_components/index.html.haml_spec.rb
=> 321 filter by assignee

app/controllers/text_components_controller.rb, app/views/text_components/index.html.haml, app/views/text_components/show.html.haml, features/step_definitions/steps.rb, features/text_components/show.feature, spec/views/text_components/show.html.haml_spec.rb
=> 312 edit modal in show

app/controllers/application_controller.rb, app/models/text_component.rb, app/models/user.rb, app/views/layouts/application.html.haml, app/views/text_components/_form.html.haml, app/views/text_components/_text_component.html.haml, app/views/text_components/index.html.haml, app/views/users/registrations/edit.html.erb, app/views/users/registrations/new.html.erb, config/initializers/devise.rb, db/migrate/20170526140811_add_name_to_users.rb, db/schema.rb, features/step_definitions/steps.rb, features/text_components/assignee.feature, features/users/username_required.feature, spec/factories/users.rb, spec/models/user_spec.rb
=> 362 assignee name

app/decorators/event_decorator.rb, app/decorators/sensor_decorator.rb, app/lib/text/renderer.rb, spec/decorators/sensor_decorator_spec.rb
=> 358 render any markup

app/controllers/chatfuel_controller.rb, app/lib/text/generator.rb, app/models/report.rb, app/views/text_components/_form.html.haml, config/routes.rb, db/schema.rb, features/channels/api.feature, features/channels/distinguish_between_reports.feature, features/channels/question_answer.feature, features/reports/different_reports.feature, features/step_definitions/steps.rb, spec/controllers/chatfuel_controller_spec.rb, spec/controllers/text_components_controller_spec.rb, spec/models/report_spec.rb, spec/requests/chatfuel_spec.rb
=> 335 390 different reports

app/views/layouts/application.html.haml, features/step_definitions/steps.rb, features/text_components/assignee.feature
don't merge until tests are green
=> change report toolbox

app/lib/text/generator.rb, app/views/records/_introduction.html.haml, app/views/records/_record.html.haml, spec/text/generator_spec.rb
=> render three most important introductions as unordered list

app/views/layouts/application.html.haml
=> Updated footer text / removed logo

app/controllers/chatfuel_controller.rb, db/schema.rb, features/channels/question_answer.feature
Added Report Id to Continue Block like in the following pattern: continue_[topic_name]_[report_id]
---
Close #394
=> 394 chatfuel continue block report

app/controllers/text_components_controller.rb, app/controllers/triggers_controller.rb, app/models/trigger.rb, app/views/triggers/_trigger_fields.html.haml, app/views/triggers/show.html.haml, db/migrate/20170625140207_rename_timeliness_constraint_to_validity_perion.rb, db/schema.rb, features/reports/timeliness_constrain.feature, features/step_definitions/steps.rb, features/triggers/timeliness_constraint.feature, spec/models/trigger_spec.rb
=> rename timeliness_constraint to validity_period

app/lib/smaxtec_api.rb, config/secrets.yml, lib/tasks/smaxtec_api.rake
=> add debug statements to rake task

app/lib/smaxtec_api.rb, db/schema.rb, fixtures/vcr_cassettes/smaxtec_api.yml, spec/lib/smaxtec_api_spec.rb
Get the Smaxtec Api values from the last 12 hours and create sensor readings if there are new values.
---
Close #439
=> 439 get smaxtec values from day

app/models/question_answer.rb, features/channels/question_answer.feature, features/reports/resi.feature, features/step_definitions/steps.rb, features/support/env.rb, features/text_components/add_question_answer.feature, features/text_components/character_limit_for_question_answers.feature, spec/models/question_answer_spec.rb
My first pull request on this project. Modified the the model QuestionAnswer and the model unit spec. Wasn't sure if the question button still needs to be renamed?
EDIT:
close #317
=> modified model QuestionAnswer to limit question to 20 characters

app/controllers/triggers_controller.rb, spec/requests/triggers_spec.rb
=> expose and fix #482

app/assets/javascripts/application.js, app/assets/javascripts/components/range.js, app/models/sensor.rb, app/models/sensor_type.rb, app/views/triggers/_condition_fields.html.haml, db/migrate/20170719205918_add_min_max_fraction_digits_to_sensor_types.rb, db/schema.rb, features/step_definitions/steps.rb, features/triggers/conditions_slider_range_is_adapted_to_sensor_type.feature, lib/tasks/update_sensor_types.rake, spec/models/sensor_type_spec.rb
close #417 
NEEDS MANUAL INTERVENTION
=> 417 min max fraction digits sensor type

app/views/text_components/_form.html.haml, db/migrate/20170718215040_add_display_name_to_topics.rb, db/schema.rb, lib/tasks/add_german_topics.rake
=> close #373, needs manual intervention

config/environments/production.rb
=> fix deprecation warnings

.travis.yml
close #507 
~~@tillprochaska encrypting the token leads to a segfault on my machine, could you try it on yours?~~
done
see: https://kuhbertha.slack.com/services/B6C199VL0?added=1
=> Travis notifications

Gemfile, app/views/layouts/application.html.haml, spec/rails_helper.rb, spec/views/layouts/application.html.haml_spec.rb
=> 505 fix links in layout

app/assets/javascripts/components/range.js, app/assets/stylesheets/components/_range.scss
=> Changed slider tooltip position

app/models/event/activation.rb, spec/models/event/activation_spec.rb
=> test+fix #550

app/decorators/event_decorator.rb, app/lib/text/renderer.rb, app/models/event.rb, app/models/event/activation.rb, app/models/trigger.rb, spec/models/event/activation_spec.rb, spec/models/event_spec.rb, spec/models/trigger_spec.rb, spec/requests/events_spec.rb, spec/text/generator_spec.rb, spec/text/renderer_spec.rb
=> 567 trigger checks events based on diary entry

app/views/text_components/_table_groupheader.html.haml, app/views/text_components/_table_row.html.haml
=> 578 Dont clip long trigger and text component titles

app/views/question_answers/_fields.html.haml, app/views/text_components/_form.html.haml, app/views/text_components/edit.html.haml, features/step_definitions/steps.rb
=> 492 Append new q/a at the end

app/decorators/event_decorator.rb, app/decorators/sensor_decorator.rb, spec/decorators/sensor_decorator_spec.rb
=> 421 Translate fallback message for missing sensory/event data

app/decorators/text_component_decorator.rb, app/models/diary_entry.rb, app/views/diary_entries/_composed_diary_entry.json.jbuilder, features/diary_entries/markup.feature, features/step_definitions/steps.rb, spec/decorators/text_component_decorator_spec.rb
=> 453 render markup for frontend

app/controllers/text_components_controller.rb, app/models/channel.rb, app/models/event.rb, app/models/sensor.rb, app/models/trigger.rb, app/models/user.rb, app/views/question_answers/_fields.html.haml, app/views/shared/text_editor/_buttons.html.haml, app/views/text_components/_form.html.haml, app/views/text_components/index.html.haml, app/views/triggers/_condition_fields.html.haml, app/views/triggers/_trigger_fields.html.haml, features/step_definitions/steps.rb
Sort channels, events, reports, sensors, triggers, users alphabetically and show only items related to the current report in text component and trigger forms.
=> 581 Sort items alphabetically by default

app/models/text_component.rb, features/reports/time_span.feature, features/step_definitions/steps.rb
=> 584 text component on time of diary entry

app/models/trigger.rb, features/reports/time_of_the_day.feature
=> 586 trigger on time checks diary entry

app/controllers/reports_controller.rb
=> limit diary entries by 3 + live entry

app/assets/stylesheets/application.scss, app/assets/stylesheets/components/_subnav.scss, app/controllers/application_controller.rb, app/views/events/edit.html.haml, app/views/events/index.html.haml, app/views/events/new.html.haml, app/views/layouts/_navbar.haml, app/views/layouts/_subnav.haml, app/views/layouts/application.html.haml, app/views/reports/present.html.haml, app/views/reports/show.html.haml, app/views/sensors/index.html.haml, app/views/sensors/show.html.haml, app/views/text_components/edit.html.haml, app/views/text_components/index.html.haml, app/views/text_components/new.html.haml, app/views/triggers/index.html.haml, features/reports/embed_livestream.feature, features/reports/preview.feature, features/reports/report_settings_page.feature, features/step_definitions/steps.rb, features/triggers/change_priority.feature, features/triggers/create_trigger.feature, spec/views/layouts/application.html.haml_spec.rb
=> [WIP] 426 breadcrumb nav

app/controllers/chatfuel_controller.rb, app/controllers/text_components_controller.rb, app/controllers/triggers_controller.rb, app/decorators/sensor_decorator.rb, app/lib/text/renderer.rb, app/models/report.rb, app/models/sensor.rb, app/models/text_component.rb, app/models/trigger.rb, app/views/text_components/_form.html.haml, app/views/text_components/edit.html.haml, app/views/triggers/_trigger_fields.html.haml, app/views/triggers/show.html.haml, db/migrate/20170819155959_move_hours_from_trigger_to_text_component.rb, db/schema.rb, features/reports/time_of_the_day.feature, features/step_definitions/steps.rb, spec/decorators/sensor_decorator_spec.rb, spec/factories/triggers.rb, spec/models/report_spec.rb, spec/models/sensor_spec.rb, spec/models/text_component_spec.rb, spec/models/trigger_spec.rb, spec/requests/text_components_spec.rb, spec/text/generator_spec.rb, spec/text/renderer_spec.rb
=> 588 text components have hours constraint

config/schedule.rb
=> close #612, needs manual intervention on the production server

app/assets/stylesheets/components/_item-table.scss, app/views/text_components/_table.html.haml, app/views/text_components/_table_groupheader.html.haml, app/views/text_components/_table_text_component.html.haml, app/views/text_components/_table_triggers.html.haml
=> Link triggers and text component names in tc table

db/migrate/20170902093444_change_from_and_to_to_float_in_conditions_table.rb, features/step_definitions/steps.rb, features/triggers/connect_trigger_with_condition.feature
Change the types of from and to in the conditions (of triggers) to floating values, so the decimals are stored and displayed.
---
Close #626
=> Changed from and to in conditions table to float

app/controllers/text_components_controller.rb, app/views/text_components/_table_row.html.haml, app/views/text_components/edit.html.haml, app/views/text_components/show.html.haml, config/routes.rb, features/step_definitions/steps.rb, features/text_components/notes_field.feature, spec/controllers/text_components_controller_spec.rb, spec/routing/text_components_routing_spec.rb, spec/views/text_components/show.html.haml_spec.rb
This is basically reverting some of the changes made in #524.
=> Bring back text components show page

app/controllers/application_controller.rb, app/views/sensors/_add_sensor_reading.haml
This is the first step to solve #633 and #634 and shows a »New Sensor Reading« button in the secondary navigation bar.
close #633
=> 663 new sensor reading button

config/schedule.rb
close https://github.com/roschaefer/story.board/issues/659
=> Remove unwanted diary entry in the afternoon

app/decorators/sensor_decorator.rb, app/models/sensor_type.rb, features/step_definitions/steps.rb, spec/decorators/sensor_decorator_spec.rb, spec/factories/sensor_types.rb, spec/models/sensor_type_spec.rb
=> 666 the number of the beast

app/assets/javascripts/application.js, app/assets/javascripts/components/form.js, app/assets/javascripts/diary_entries.coffee, app/assets/javascripts/reports.js, app/assets/javascripts/sensors.coffee, app/views/layouts/_subnav.haml, app/views/text_components/_form.html.haml
close #514 
~~sledgehammer the cucumber test - I still don't understand why only phantomjs and not chrome fails here and only after we activated turbolinks~~
=> Bring back turbolinks

app/assets/stylesheets/components/_item-table.scss, app/controllers/text_components_controller.rb, app/views/text_components/_table_text_component.html.haml, app/views/text_components/_table_triggers.html.haml, spec/views/text_components/index.html.haml_spec.rb
@drjakob requested this one again and I gave it a quick try. While it certainly needs more db queries to highlight text components that are currently active, I managed to do some optimizations. On my local machine, the perceived loading time didn’t increase too badly…
// cc @drjakob
=> 374 green flashlight

lib/tasks/update_sensor_types.rake
Change milk quantity sensortype unit to kilogram and change unit of sensortype Movement to Percent.
---
Close #678 
Close #682
=> Change milk quantity sensortype to kilogram

app/models/text_component.rb, lib/tasks/update_timeframes.rake
Change evening timeframe from 18-0h, change nights timeframe to 0-6h as proposed by @drjakob in #677 
@tillprochaska Do you know if changing the timeframes in the text_component model is sufficient, or do I need to make more changes for the new timeframes to get triggered properly?
--- 
Close #677
=> Change evening timeframe from 18-0h, change nights timeframe to 0-6h

db/migrate/20170911185434_update_timeframes.rb
=> 687 update diary entries timeframes

db/migrate/20170910091746_change_validity_period_to_float_in_triggers.rb, features/step_definitions/steps.rb, features/triggers/timeliness_constraint.feature
For the validity period to accept floating numbers it needs to be changed to a float field in the db. I also added a cucumber test to verity that the validity period accepts float numbers.
---
Close #683
=> 683 validity period change to float

app/controllers/sensors_controller.rb, app/controllers/text_components_controller.rb, app/controllers/triggers_controller.rb, spec/factories/text_components.rb, spec/requests/sensors_spec.rb, spec/requests/text_components_spec.rb, spec/requests/triggers_spec.rb, spec/support/shared_examples/report_namespaced_controller.rb
=> fix #669 for sensors, triggers and text_components

app/assets/stylesheets/components/_item-table.scss, app/controllers/text_components_controller.rb, app/decorators/text_component_decorator.rb, app/models/text_component.rb, app/views/text_components/_table_text_component.html.haml, spec/views/text_components/index.html.haml_spec.rb
=> Different highlight colors depending on publication status

app/views/text_components/_form.html.haml, app/views/text_components/show.html.haml
Show the image thumbnail (instead of the full image) in the edit text component view and also show the thumbnail in the show text component view (or show a help text if no image has been uploaded so far).
---
Close #671 
Close #662
=> Show thumbnail in edit text component & in show text component view

app/views/actuators/show.html.haml, app/views/diary_entries/show.html.haml, app/views/events/_form.html.haml, app/views/events/edit.html.haml, app/views/events/new.html.haml, app/views/reports/_form.html.haml, app/views/reports/edit.html.haml, app/views/sensors/_form.html.haml, app/views/sensors/edit.html.haml, app/views/text_components/show.html.haml, app/views/triggers/_trigger_fields.html.haml
Turn "back" links into buttons of class btn-secondary and fix the layout / margin between the buttons.
``
---
Close #702
=> Change back links to buttons and optimize layout

app/controllers/application_controller.rb, app/controllers/text_components_controller.rb, app/models/channel.rb, app/views/layouts/_subnav.haml, app/views/text_components/_form.html.haml, config/routes.rb, spec/controllers/text_components_controller_spec.rb
=> 615 duplicate text components

app/assets/stylesheets/components/_breadcrumb-nav.scss, app/assets/stylesheets/components/_subnav.scss, app/controllers/application_controller.rb, app/views/events/edit.html.haml, app/views/events/new.html.haml, app/views/layouts/_subnav.haml, app/views/sensors/edit.html.haml, app/views/sensors/new.html.haml, app/views/sensors/show.html.haml, app/views/text_components/edit.html.haml, app/views/text_components/new.html.haml, app/views/text_components/show.html.haml, app/views/triggers/edit.html.haml, app/views/triggers/new.html.haml, app/views/triggers/show.html.haml
=> 622 enhanced breadcrumb texts

app/controllers/sensor_readings_controller.rb, app/views/sensor/readings/_reading.html.haml, app/views/sensor/readings/destroy.js.erb, app/views/sensors/show.html.haml, config/routes.rb, features/sensor_readings/add_sensor_reading_manually.feature, features/step_definitions/steps.rb
Add button / link to delete single sensor reading. 
---
Close #711
=> 711 button to delete sensor values

config/schedule.rb, features/step_definitions/steps.rb, spec/jobs/whenever_spec.rb
This will stop the generation of new diary entries
close #718
=> Merge at 2017-10-03 15:00
