README.md, db/seeds.rb
fix: #32 
@drjakob I haven't abbreviated the sensor type properties. We can still add a new attribute if necessary. Or anything else, that is common to all sensors of a certain class or type.
=> create seed data for sensor types

app/controllers/reports_controller.rb, app/views/reports/_form.html.haml, features/reports/report_settings_page.feature, features/step_definitions/steps.rb
@drjakob I have a question: #82 explains that the "Cow name" should be set for later use in the report. This PR allows to change the `report name`. E.g. from "Kuh Bertha" to "Kuh Sieglinde". Is this enough to fulfill the requirement? Or to be more precise, shall we use the name of the report in the generated text?
=> 82 set report name

db/migrate/20170402092445_create_default_channels.rb, db/schema.rb, db/seeds.rb
Leave Factories in place, because in testing the database is often reset, so default channels won't be there at all
fixes #297
=> add migration that creates default channels

.travis.yml, app/models/channel.rb, db/migrate/20170402092445_create_default_channels.rb, db/migrate/20170419204307_add_unique_constraint_to_channel.rb, db/schema.rb, features/step_definitions/steps.rb, features/support/env.rb, spec/controllers/channels_controller_spec.rb, spec/controllers/chatfuel_controller_spec.rb, spec/controllers/reports_controller_spec.rb, spec/factories/channels.rb, spec/factories/text_components.rb, spec/jobs/whenever_spec.rb, spec/models/channel_spec.rb, spec/models/report_spec.rb, spec/models/text_component_spec.rb, spec/text/generator_spec.rb
@matthib you are already familiar with issues of static data
This does not change anything from the user perspective. It makes sure that no channels and no reports will be created in tests unless it is explicitly asked for. We have a migration for static data so we assume static data to be accessible in our tests. As another sanity check this introduces a unique constraint on the channels, so we don't create channels with the same name by accident.
=> Use static data in tests

app/controllers/chatfuel_controller.rb, config/routes.rb, features/channels/question_answer.feature, features/step_definitions/steps.rb, spec/controllers/chatfuel_controller_spec.rb, spec/requests/chatfuel_spec.rb
This is the pull request for issue #248.
If a text component contains question and answers, send button with question to chatfuel. As long as there are more questions, keep sending the answer of the last question and a button for the new question.
The formatting is not always right in this commit (indentation with 4 chars vs. 2 chars), this needs to be addressed later.
---
close #248
=> Chatfuel questions and answers

app/assets/javascripts/text_components.coffee, app/assets/javascripts/text_components.js, app/assets/stylesheets/text_components.scss, app/controllers/text_components_controller.rb, app/views/question_answers/_fields.html.haml, app/views/text_components/_form.html.haml, spec/views/text_components/index.html.haml_spec.rb
I added dropdowns for events and sensors to add the corresponsing markup to the text fields in the edit modal and slightly changed the appearance of the toolbar improving the ux especially with long forms.
--
#207,  #325
=> Added ingredients menu for sensors and events

app/controllers/chatfuel_controller.rb, features/channels/question_answer.feature, spec/requests/chatfuel_spec.rb
With the last answer of a question & answer list a button is sent linking to a block (name pattern for the block is cont_+[topic]) in order to continue with the conversation.
---
Close #340
=> Button with link to block after last question and answer

app/controllers/chatfuel_controller.rb, features/channels/question_answer.feature
I changed the pattern of the continue block from cont_topic.id to continue_topic.id
I didn't see that the other branch was already merged, please delete this pull request if the merged branch is suficcient.
Referencing #340
=> Changed block name to continue_topic.id

app/controllers/chatfuel_controller.rb, features/channels/question_answer.feature, spec/requests/chatfuel_spec.rb
Instead of linking to a continue block, the user now gets redirected when questions and answers are empty.
Referencing #340
=> Show last answer & redirect if question answers are empty

app/controllers/text_components_controller.rb, app/views/text_components/_form.html.haml, app/views/text_components/index.html.haml, app/views/triggers/_condition_fields.html.haml, app/views/triggers/_trigger_fields.html.haml
Select options in forms related to text components or triggers will now be sorted alphabetically.
Sorting for users selects is case-insensitive. Options for all other selects are displayed in default alphabetic order to avoid affecting query performance.
close #355
=> 355 sort dropdowns

app/controllers/chatfuel_controller.rb, spec/requests/chatfuel_spec.rb
Fixed the bug where the Chatfuel API request would always return the same text component, not looking for the requested topic.
Now the topic request looks for the topic with the corresponding topic name and returns the first text component of this topic.
---
Close #385
=> 385 Chatfuel api request return text_component based on topic.name

app/controllers/chatfuel_controller.rb, spec/controllers/chatfuel_controller_spec.rb
Extended the chatfuel controller to render markup in questions and answers for the chatbot as well.
close #358
=> 358 render any markup

app/models/question_answer.rb
fix #414 
@matthib @sebroeder @tillprochaska 
I enforce an order on all `QuestionAnswer`s with a default scope here. This has an effect on pretty much everything related to `QuestionAnswer`s, every call like `text_component.question_answers` will return the question answers ordered by `created_at`. `default_scope` is a source of errors and should be used with the utmost precaution. AFAIK as long as we edit all question-answers through the text component like a "stack" this should be no problem. What is your opinion on it? Do you think it's safe to use?
=> default scope to define a natural ordering of question answers

app/lib/smaxtec_api.rb, db/migrate/20170625165032_add_smaxtec_timestamp_to_sensor_readings.rb, db/migrate/20170625170112_add_smaxtec_timestamp_to_sensor_readings.rb, db/schema.rb, spec/lib/smaxtec_api_spec.rb
Prevent duplicate smaxtec sensor readings by adding smaxtec_timestamp to sensor reading table & check if combination of smactec_timestamp and sensor_id already exists before creating new sensor reading.
---
Close #443
=> 443 prevent duplicate smaxtec sensor readings

app/lib/smaxtec_api.rb, db/seeds.rb
This commit adds the sensor types for ph Value und and movement together with their Smaxtec API equivalents.
I was not 100% about the Smaxtec value for movement, but I think it is act which stands for activity probably. There is also the value act_index which seems to also be an activity index, but act_index is measured in percent and act is measured metrically.
@drjakob Should I double check which is the right value with the Smaxtec guys?
Also when digging through the data of the different cows I found out that not every cow has the same metrics / data available at their sensors. Some don't have ph value and some don't have a movement value available, so it might happen that we don't get all the metrics from all the cows.
---
Close #393 
Close #392
=> added ph value and movement to sensor types

app/lib/smaxtec_api.rb, lib/tasks/smaxtec_api.rake
I added the smaxtec sensortype via rake task 'smaxtec_api:add_smaxtec_sensortypes' and changed the smaxtec sensor metric mapping for the movement sensor to 'act_index' (-> 'act' activity value smoothed and stretched from 0-100 in %).
---
Close #459
=> Add sensor types & change movement smaxtec mapping metric

app/models/sensor_type.rb
This will e.g. order SensorTypes in the Sensor#edit form by property. A default scope has global effect, but I think it's safe to use as long it's just the `order`.
=> SensorType: default order

app/controllers/diary_entries_controller.rb, app/controllers/reports_controller.rb, app/lib/text/generator.rb, app/views/reports/present.html.haml, lib/tasks/archive.rake, spec/controllers/diary_entries_controller_spec.rb, spec/controllers/reports_controller_spec.rb
That was a nice bug :bug: 
Diary entries at the `diary_entries/` route as well as on the landing page did not belong to the given `@report`. It was the first report instead. Also the `rake` task never produced any other diary entries except those for the first report
=> 460 wrong report id in diaries controller

Gemfile, Gemfile.lock, config/application.rb
close #470 
On my machine, this is what `curl -H "Origin:*" -I http://localhost:3000/` gives me:
```
HTTP/1.1 301 Moved Permanently
Access-Control-Allow-Origin: *
Access-Control-Allow-Methods: GET, POST, OPTIONS
Access-Control-Max-Age: 1728000
Location: http://localhost:3000/reports/current
Content-Type: text/html
Cache-Control: no-cache
X-Request-Id: a635f5a4-03dd-4e11-9a29-0d2cdeb188fb
X-Runtime: 0.005417
Vary: Origin
Content-Length: 103
```
@davidLichtenberger do you need any more HTTP methods like `PUT`, `PATCH`, `DELETE`?
=> 470 allow cors

app/lib/smaxtec_api.rb, fixtures/vcr_cassettes/smaxtec_api.yml
Use Smaxtec Live API endpoint by changing the url the system is sending queries to update the sensory data to.
---
Close #467
=> change url of smaxtec api to use live api

app/assets/javascripts/components/range.js, app/assets/stylesheets/components/_range.scss
@roschaefer: You can now reinitialize the range slider at any time.
```javascript
$('.selector').data('range').reinit({
min: -10,
max: -5,
step: .1
})
```
This will keep the rangeslider’s value or set it to the new min/max value if it doesn’t lie in the value range.
Of course you can also set a new value in the same go:
```javascript
$('.selector').data('range').reinit({
min: -10,
max: -5,
step: .1
}).value('-9,-6')
```
And you can also completely reset the slider to restore the initial state (which is what the `reinit` method uses internally):
```javascript
$('.selector').data('range').destroy()
```
=> Added destroy and reinit methods to Range component

app/decorators/sensor_decorator.rb, features/triggers/write_about_sensor_value.feature, spec/controllers/chatfuel_controller_spec.rb, spec/decorators/sensor_decorator_spec.rb, spec/text/generator_spec.rb, spec/text/renderer_spec.rb
close #384
@tillprochaska after I've seen the types of units, I would suggest to always put a space between value and unit to have a clear separation.
=> close #384

app/assets/stylesheets/components/_field.scss, app/views/text_components/_form.html.haml
@drjakob: Okay, I made the main input larger by default. Maybe that’s already enough. Setting it to 8 lines makes the form unecessary long and in the consequence harder to scan, though. Maybe something like this could help to give a quick visual impression of the text fields while still keeping the form short.
And if your editors are looking for an indicator of text length, a character/word count might be a better idea instead (and is btw pretty cheap to implement).
close #491
=> Larger textarea for main content in tc form

app/models/sensor.rb, db/schema.rb
The address field of a sensor is no longer required, but still validated as unique.
Is this what you hand in mind @roschaefer?
---
Close #449
=> removed presence validation for sensor address field

app/assets/javascripts/sensors.coffee, app/controllers/sensor_readings_controller.rb, app/views/sensor/readings/create.js.erb, app/views/sensors/_add_sensor_reading.haml, features/sensor_readings/add_sensor_reading_manually.feature, features/sensor_readings/generate_debug_sample_data.feature, features/step_definitions/steps.rb
The purpose of this PR is to improve the manual input of sensor readings by offering select fields to select the date / time of the sensor reading (with current date / time preselected) and refreshing the page when an entry has been made, in order to give a visual feedback of the new record (-> show the user that entering the sensor reading worked).
At the moment the text field for date / time has been replaced by select fields with the preselected current time.
The feature that needs to be implemented yet, is the page reload when entering a new sensor reading. This is probably a bit tricky, because the form is set to remote (Ajax) and the create method for the sensor_readings expects / returns json values (https://github.com/roschaefer/story.board/blob/master/app/controllers/sensor_readin …
=> [WIP]  Improved input fields for manual sensor inputs

Gemfile.lock
The `Capfile` is locked to version 3.9.0 but the `Gemfile.lock` has version 3.8.2 so Capistrano tasks will not run. Update Capistrano to version 3.9.0 to fix this mismatch.
=> Update Capistrano to 3.9.0

app/models/sensor.rb, db/migrate/20170730125054_add_unique_constraint_to_animal_id.rb, db/schema.rb, spec/models/sensor_spec.rb
This PR solves the issue #500 "Bug Creating Sensors: Animal ID should never be required". The problem was that the Animal Id is validated to be unique for a Sensor Type together with an Animal Id. If the Animal Id is empty for one Sensor Type, there can't exist another similar Sensor Type with an empty Animal Id. 
This is solved by allowing the Animal Id to be blank (empty).
---
Close #500
=> Allow blank animal ids for sensors

public/robots.txt
The CMS backend content that is not yet behind a login shows up in search engine results.
Disallow all crawlers to index the CMS backend. This is the most restrictive setting possible.
Consider this a workaround and not a full replacement for a password protected login.
=> Disallow indexing of the CMS backend in `robots.txt`

spec/models/text_component_spec.rb
The contexts 'given one trigger' and 'given many triggers' where nested below 'triggers empty' which is a logical contradiction. Put them on the same nesting level as 'triggers empty' instead.
Output of `rspec -f documentation` before the change:
```
TextComponent
#active?
triggers empty
should equal true
given one trigger
active trigger
should equal true
inactive trigger
should equal false
given many triggers
some are active, some are inactive
should equal false
all active
should equal true
```
And after the change:
```
TextComponent
#active?
triggers empty
should equal true
given one trigger
active trigger
should equal true
inactive trigger
should equal false
given many triggers
some are active, some are inactive
should equal false
all active
should equal true
```
=> Fix context nesting in `text_component_spec.rb`

lib/tasks/smaxtec_api.rake
Change selectable values for smaxtec event sensortypes to 0 / 1 with rake task.
---
Close #597
=> Change smaxtec event sensortypes possible values to 0 or 1 (bool)

app/models/trigger.rb, features/reports/time_travel.feature, spec/models/report_spec.rb
This is the proposed fix for the "TRIGGER for ALERTS NOT WORKING" problem as stated in #627.
Please mind that this changes the behavior of consecutive trigger values, as @roschaefer pointed out. This could lead to serious side effects, if there are triggers who have consecutive values e.g. trigger1 10-20, trigger2 20-30. When the value of 20 is hit, both triggers will now fire.
---
Close #627
=> Make trigger fire if sensor reading value <= max value

Gemfile, Gemfile.lock, app/controllers/diary_entries_controller.rb, config/environments/production.rb, config/schedule.rb, lib/tasks/cache.rake
close #621 
To give a little context here: Our app already servers static files, [which is discouraged by the way](http://guides.rubyonrails.org/configuring.html).
> config.public_file_server.enabled configures Rails to serve static files from the public directory. This option defaults to true, but in the production environment it is set to false because the server software (e.g. NGINX or Apache) used to run the application should serve static files instead. If you are running or testing your app in production mode using WEBrick (it is not recommended to use WEBrick in production) set the option to true. Otherwise, you won't be able to use page caching and request for files that exist under the public directory.
The gem will now create cached files directly into the `public` folder, since …
=> Setup page caching

app/views/text_components/_form.html.haml
Fix text component showing the wrong selected report. Before it showed the globally selected report (@report.id), now it shows the report selected for the text component (@text_component.report_id).
---
Close #638
=> 638 fix text component selecting report

app/views/reports/show.html.haml
The back button is actually pretty useless in this view as we don’t have an index view for reports and I can’t think of a sensible target for that link. I’ve removed it to avoid confusion. Please merge if you’re okay with this solution.
=> 644 Remove back button in Report#show

app/assets/stylesheets/components/_item-table.scss, app/controllers/text_components_controller.rb, app/views/text_components/_table.html.haml, app/views/text_components/_table_row.html.haml, spec/views/text_components/index.html.haml_spec.rb
The timeframe will now be displayed in the text components listing as well.
@matthib: I know this [regex replacement](https://github.com/roschaefer/story.board/blob/606_show_timeframe/app/views/text_components/_table_row.html.haml#L14) is quite dirty, I didn’t want to refactor the[ part of the model](https://github.com/roschaefer/story.board/blob/606_show_timeframe/app/models/text_component.rb#L2-L9) where those labels are generated…
@drjakob: Unfortunately I didn’t find a good way to indicate the timeframe using icons or anything else, but I think simple text is actually a good and unambigous solution in this case.
close #606
=> 606 show timeframe

app/models/trigger.rb, spec/models/diary_entry/html_output_spec.rb, spec/models/text_component_spec.rb, spec/requests/diary_entries_spec.rb, spec/text/sorter_spec.rb
I added two new priorities at the end of the list: totally_boring and always_on_top. Technically always_on_top has just the highest priority, so if there are two always_on_top priorities, just one can be "always on top". But as @drjakob stated in the original issue, this priority is used rarely and exclusively, so there is not much of a conflict.
---
Close #642
=> Add new priorities totally_boring and always_on_top

app/models/text_component.rb, app/views/text_components/_text_component.json.jbuilder, features/diary_entries/markup.feature, features/diary_entries/show.feature
The paperclip gem generates thumbnails for the images in the text component: a big one with a width of 1000px and a small one with a width of 620px. I added the url to these thumbnails in the json that is sent to the frontend. 
The original image can still be accessed via image_url, the big thumbnail via image_url_big and the small one via image_url_small.
=> Add big & small thumbnail image url to text component json

app/models/text_component.rb
This adds a file size validation for the text component image upload in order to prevent the reporters from uploading images that are too big for the server too handle.
The image maximum file size is set to 20 MB with this commit.
=> Add file size validation for image upload
